admin_claimed_badge_index:
    path:     /
    defaults: { _controller: "GameBundle:BadgeCompletion:index" }
    methods:  GET

admin_claimed_badge_reject:
    path:     /{id}/reject
    defaults: { _controller: "GameBundle:BadgeCompletion:reject" }
    methods:  GET

admin_claimed_badge_send_to_vote:
    path:     /{id}/send-to-vote
    defaults: { _controller: "GameBundle:BadgeCompletion:sendToTheCouncil" }
    methods:  GET

admin_claimed_badge_accept:
    path:     /{id}/accept
    defaults: { _controller: "GameBundle:BadgeCompletion:accept" }
    methods:  GET
