Badger\GameBundle\Entity\QuestCompletion:
    properties:
        user:
            - NotNull: ~
        quest:
            - NotNull: ~
        completionDate:
            - NotNull: ~
        pending:
            - NotNull: ~
