hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

github_login:
    path: /login/check-github

github_connect:
    path: /connect/github

google_login:
    path: /login/check-google

user_bundle:
    resource: '@UserBundle/Resources/config/routing.yml'

gate_bundle:
    resource: '@GateBundle/Resources/config/routing.yml'

game_bundle:
    resource: '@GameBundle/Resources/config/routing.yml'

tag_bundle:
    resource: "@TagBundle/Resources/config/routing.yml"
