Badger\GameBundle\Entity\Badge:
    type: entity
    table: badges
    repositoryClass: Badger\GameBundle\Doctrine\Repository\BadgeRepository
    fields:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 1024
            nullable: false
        imagePath:
            type: string
            length: 1024
            nullable: true
    manyToMany:
        tags:
            targetEntity: Badger\TagBundle\Entity\Tag
            inversedBy: badges
            joinTable:
                name: badges_tags
                joinColumns:
                    badge_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
