Badger\GameBundle\Entity\QuestCompletion:
    type: entity
    table: quest_completions
    repositoryClass: Badger\GameBundle\Doctrine\Repository\QuestCompletionRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        completionDate:
            type: datetime
            nullable: false
        pending:
            type: boolean
            nullable: false
    manyToOne:
        user:
            targetEntity: Badger\UserBundle\Entity\User
            cascade: ['persist']
            joinColumn:
                user_id:
                    referencedColumnName: id
        quest:
            targetEntity: Badger\GameBundle\Entity\Quest
            inversedBy: completions
            joinColumn:
                quest_id:
                    referencedColumnName: id
