parameters:
    badger.game.saver.badge_completion.class: Badger\Bundle\GameBundle\Doctrine\Saver\BadgeCompletionSaver

services:
    badger.game.saver.badge:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Badge'

    badger.game.saver.badge_completion:
        class: '%badger.game.saver.badge_completion.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Badger\Bundle\GameBundle\Entity\BadgeCompletion'

    badger.game.saver.quest:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Quest'

    badger.game.saver.quest_completion:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\QuestCompletion'

    badger.game.saver.adventure:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Adventure'

    badger.game.saver.adventure_step_completion:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\AdventureStepCompletion'

    badger.game.saver.tag:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Tag'

    badger.game.saver.votable_item:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\VotableItem'

    badger.game.saver.vote:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Vote'
