parameters:
    badger.game.helper.badge_vote_engine.class: Badger\GameBundle\Vote\BadgeVoteEngine

services:
    badger.game.helper.badge_vote_engine:
        class: %badger.game.helper.badge_vote_engine.class%
        arguments:
            - '@badger.game.repository.badge_vote'
            - '@badger.game.saver.badge_vote'
