services:
    badger.user.saver.user:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\UserBundle\Entity\User'
